---
image: dablang/dablangenv:0.5
before_script:
- gem install bundler
- bundle install --path=/cache/bundler
stages:
- format
- prebuild
- build
- test
".build_base":
  stage: build
  tags: &2
  - ruby
  script: &3
  - bundle exec rake bin/cvm
  - bundle exec rake bin/cdisasm
  - bundle exec rake bin/cdumpcov
  artifacts: &4
    paths:
    - bin/*
    - build/*
    - tmp/c_files.txt
    expire_in: 1 week
".test_base":
  stage: test
  tags: &1
  - ruby
".test_base_spec":
  stage: test
  tags: *1
  script: &6
  - bundle exec rake spec
".test_base_vm_spec":
  stage: test
  tags: *1
  script: &8
  - bundle exec rake vm_spec
".test_base_disasm_spec":
  stage: test
  tags: *1
  script: &9
  - bundle exec rake disasm_spec
".test_base_dumpcov_spec":
  stage: test
  tags: *1
  script: &10
  - bundle exec rake dumpcov_spec
".test_base_cov_spec":
  stage: test
  tags: *1
  script: &11
  - bundle exec rake cov_spec
".test_base_debug_spec":
  stage: test
  tags: *1
  script: &12
  - bundle exec rake debug_spec
StdlibFormatCheck:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rake format:stdlib_check
SortFilesCheck:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rake format:sortfiles_check
AsmSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake asm_spec
FormatSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake format_spec
RSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rspec
Rubocop:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rubocop
ClangFormat:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rake format:cpp_check
SortCheck:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rake format:sort_check
".env_g_4_7":
  variables: &5
    CXX: g++-4.7
".env_clang_3_5":
  variables: &13
    CXX: clang++-3.5
Build g++-4.7:
  stage: build
  tags: *2
  script: *3
  artifacts: *4
  variables: *5
Test g++-4.7 spec 0 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '0'
    CI_PARALLEL_TOTAL: '10'
  dependencies: &7
  - Build g++-4.7
Test g++-4.7 spec 1 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '1'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 2 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '2'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 3 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '3'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 4 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '4'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 5 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '5'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 6 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '6'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 7 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '7'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 8 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '8'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 spec 9 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.7
    CI_PARALLEL_INDEX: '9'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *7
Test g++-4.7 vm_spec:
  stage: test
  tags: *1
  script: *8
  variables: *5
  dependencies:
  - Build g++-4.7
Test g++-4.7 disasm_spec:
  stage: test
  tags: *1
  script: *9
  variables: *5
  dependencies:
  - Build g++-4.7
Test g++-4.7 dumpcov_spec:
  stage: test
  tags: *1
  script: *10
  variables: *5
  dependencies:
  - Build g++-4.7
Test g++-4.7 cov_spec:
  stage: test
  tags: *1
  script: *11
  variables: *5
  dependencies:
  - Build g++-4.7
Test g++-4.7 debug_spec:
  stage: test
  tags: *1
  script: *12
  variables: *5
  dependencies:
  - Build g++-4.7
Build clang++-3.5:
  stage: build
  tags: *2
  script: *3
  artifacts: *4
  variables: *13
Test clang++-3.5 spec 0 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '0'
    CI_PARALLEL_TOTAL: '10'
  dependencies: &14
  - Build clang++-3.5
Test clang++-3.5 spec 1 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '1'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 2 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '2'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 3 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '3'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 4 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '4'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 5 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '5'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 6 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '6'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 7 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '7'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 8 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '8'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 spec 9 10:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CI_PARALLEL_INDEX: '9'
    CI_PARALLEL_TOTAL: '10'
  dependencies: *14
Test clang++-3.5 vm_spec:
  stage: test
  tags: *1
  script: *8
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 disasm_spec:
  stage: test
  tags: *1
  script: *9
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 dumpcov_spec:
  stage: test
  tags: *1
  script: *10
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 cov_spec:
  stage: test
  tags: *1
  script: *11
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 debug_spec:
  stage: test
  tags: *1
  script: *12
  variables: *13
  dependencies:
  - Build clang++-3.5
