---
image: dablang/dablangenv:0.8
before_script:
- bundle install --path=/cache/bundler
stages:
- format
- prebuild
- build
- test
".build_base":
  stage: build
  tags: &2
  - ruby
  script: &3
  - bundle exec rake bin/cvm
  - bundle exec rake bin/cdisasm
  - bundle exec rake bin/cdumpcov
  artifacts: &4
    paths:
    - bin/*
    - build/*
    - tmp/c_files.txt
    expire_in: 1 week
".test_base":
  stage: test
  tags: &1
  - ruby
".test_base_spec":
  stage: test
  tags: *1
  script: &6
  - bundle exec rake spec
".test_base_vm_spec":
  stage: test
  tags: *1
  script: &8
  - bundle exec rake vm_spec
".test_base_disasm_spec":
  stage: test
  tags: *1
  script: &9
  - bundle exec rake disasm_spec
".test_base_dumpcov_spec":
  stage: test
  tags: *1
  script: &10
  - bundle exec rake dumpcov_spec
".test_base_cov_spec":
  stage: test
  tags: *1
  script: &11
  - bundle exec rake cov_spec
".test_base_debug_spec":
  stage: test
  tags: *1
  script: &12
  - bundle exec rake debug_spec
StdlibFormatCheck:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rake format:stdlib_check
SortFilesCheck:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rake format:sortfiles_check
AsmSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake asm_spec
FormatSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake format_spec
RSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rspec
CompilerPerformanceSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake compiler_performance_spec
BuildExamplesSpec:
  stage: prebuild
  tags:
  - ruby
  script:
  - bundle exec rake build_examples_spec
Rubocop:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rubocop
ClangFormat:
  stage: format
  tags:
  - ruby
  variables:
    CLANG_FORMAT: clang-format-4.0
  script:
  - bundle exec rake format:cpp_check
SortCheck:
  stage: format
  tags:
  - ruby
  script:
  - bundle exec rake format:sort_check
".env_g_4_8":
  variables: &5
    CXX: g++-4.8
    CLANG_FORMAT: clang-format-4.0
".env_clang_3_5":
  variables: &13
    CXX: clang++-3.5
    CLANG_FORMAT: clang-format-4.0
Build g++-4.8:
  stage: build
  tags: *2
  script: *3
  artifacts: *4
  variables: *5
Test g++-4.8 spec 0 2:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.8
    CLANG_FORMAT: clang-format-4.0
    CI_PARALLEL_INDEX: '0'
    CI_PARALLEL_TOTAL: '2'
  dependencies: &7
  - Build g++-4.8
Test g++-4.8 spec 1 2:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: g++-4.8
    CLANG_FORMAT: clang-format-4.0
    CI_PARALLEL_INDEX: '1'
    CI_PARALLEL_TOTAL: '2'
  dependencies: *7
Test g++-4.8 vm_spec:
  stage: test
  tags: *1
  script: *8
  variables: *5
  dependencies:
  - Build g++-4.8
Test g++-4.8 disasm_spec:
  stage: test
  tags: *1
  script: *9
  variables: *5
  dependencies:
  - Build g++-4.8
Test g++-4.8 dumpcov_spec:
  stage: test
  tags: *1
  script: *10
  variables: *5
  dependencies:
  - Build g++-4.8
Test g++-4.8 cov_spec:
  stage: test
  tags: *1
  script: *11
  variables: *5
  dependencies:
  - Build g++-4.8
Test g++-4.8 debug_spec:
  stage: test
  tags: *1
  script: *12
  variables: *5
  dependencies:
  - Build g++-4.8
Build clang++-3.5:
  stage: build
  tags: *2
  script: *3
  artifacts: *4
  variables: *13
Test clang++-3.5 spec 0 2:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CLANG_FORMAT: clang-format-4.0
    CI_PARALLEL_INDEX: '0'
    CI_PARALLEL_TOTAL: '2'
  dependencies: &14
  - Build clang++-3.5
Test clang++-3.5 spec 1 2:
  stage: test
  tags: *1
  script: *6
  variables:
    CXX: clang++-3.5
    CLANG_FORMAT: clang-format-4.0
    CI_PARALLEL_INDEX: '1'
    CI_PARALLEL_TOTAL: '2'
  dependencies: *14
Test clang++-3.5 vm_spec:
  stage: test
  tags: *1
  script: *8
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 disasm_spec:
  stage: test
  tags: *1
  script: *9
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 dumpcov_spec:
  stage: test
  tags: *1
  script: *10
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 cov_spec:
  stage: test
  tags: *1
  script: *11
  variables: *13
  dependencies:
  - Build clang++-3.5
Test clang++-3.5 debug_spec:
  stage: test
  tags: *1
  script: *12
  variables: *13
  dependencies:
  - Build clang++-3.5
