AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Style/SymbolArray:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: compact

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/AccessorMethodName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false
  EnforcedStyle: align_braces

Layout/IndentationConsistency:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericLiterals:
  Enabled: false

Lint/Void:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/EndAlignment:
  AutoCorrect: true

Layout/DefEndAlignment:
  AutoCorrect: true

Style/RaiseArgs:
  EnforcedStyle: compact

Style/FormatString:
  EnforcedStyle: sprintf

Metrics/ClassLength:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: false

Style/For:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/Loop:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Security/Open:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/GlobalStdStream:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# to be re-enabled
Style/ClassEqualityComparison:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Lint/UselessMethodDefinition:
  Enabled: false
Lint/ElseLayout:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
