require 'os'
require 'rbconfig'
require 'shellwords'

if ENV['COVERAGE']
  require 'simplecov'
  SimpleCov.start
  SimpleCov.command_name 'Rakefile'
end

require_relative 'setup'
require_relative 'lib/dab/regex_engine_dependency'
require_relative 'src/shared/system'

$autorun = false

require_relative 'src/frontend/frontend'
require_relative 'src/frontend/frontend_asm'
require_relative 'src/frontend/frontend_format'
require_relative 'src/frontend/frontend_vm'
require_relative 'src/frontend/frontend_debug'
require_relative 'src/frontend/frontend_minitest'
require_relative 'src/frontend/frontend_modern_source'

$sources = Dir.glob('src/**/*.rb')

$toolset = ENV['TOOLSET'] || 'gmake'

def mangle_bin(bin, library: false)
  if library
    bin = if OS.windows?
            "#{bin}.dll"
          else
            dyext = OS.linux? ? 'so' : 'dylib'
            "lib#{bin}.#{dyext}"
          end
  end
  bin = "bin/#{bin}"
  bin += '.exe' if OS.windows? && !library
  bin
end

clang_format_app = ENV['CLANG_FORMAT'] || 'clang-format'
premake = ENV['PREMAKE'] || 'premake5'
$devenv = ENV['DEVENV'] || 'devenv'
$msbuild = ENV['MSBUILD'] || 'msbuild'

premake = "#{premake} #{$toolset}"
premake_source = 'premake5.lua'
version_file = 'VERSION'
cvm = mangle_bin('cvm')
cdisasm = mangle_bin('cdisasm')
cdumpcov = mangle_bin('cdumpcov')
cffitest = mangle_bin('cffitest', library: true)

opcodes = 'src/shared/opcodes.rb'
classes_file = 'src/shared/classes.rb'

cvm_opcodes = 'src/cshared/opcodes.h'
cvm_classes = 'src/cshared/classes.h'
opcode_task = 'tasks/opcodelist.rb'
classes_task = 'tasks/classes.rb'

cvm_syscalls = 'src/cshared/opcodes_syscalls.h'
cvm_syscalls_task = 'tasks/syscalls.rb'

cvm_opcodes_debug = 'src/cshared/opcodes_debug.h'
opcode_debug_task = 'tasks/opcode_debuglist.rb'

opcode_docs_file = 'docs/vm/opcodes.md'
opcode_docs_task = 'tasks/opcode_docs.rb'

classes_docs_file = './docs/classes.md'
classes_docs_task = './tasks/classes_docs.rb'

ffi_file = './src/cvm/ffi_signatures.h'
ffi_task = './tasks/ffi_signatures.rb'

regex_engine_config = 'config/regex_engine.json'
regex_engine_dependency = 'lib/dab/regex_engine_dependency.rb'
regex_engine_marker = 'build/dependencies/pcre2-10.47/.dab-regex-engine-ready.json'

csources_type = {}
%w[cvm cdisasm cdumpcov cffitest].each do |ctype|
  sources = Dir.glob("src/{#{ctype},cshared}/**/*")
  sources = Dir.glob("src/{#{ctype}}/**/*") if ctype == 'cffitest'
  sources += [cvm_opcodes, cvm_classes, cvm_opcodes_debug, cvm_syscalls]
  if ctype == 'cvm'
    sources += [regex_engine_config, regex_engine_dependency, regex_engine_marker]
  end
  sources.sort!
  sources.uniq!

  csources_type[ctype] = sources
end

csources = csources_type.values.reduce(&:|)
csources.sort!
csources.uniq!

filelist_body_new = "#{csources.join("\n")}\nVERSION=#{File.read(version_file).strip}"

original_makefile = case $toolset
                    when 'gmake'
                      'build/Makefile'
                    when /vs\d+/
                      'build/Dab.sln'
                    end

makefile = case $toolset
           when 'gmake'
             "build/Makefile.#{Digest::SHA256.hexdigest(filelist_body_new)}"
           when /vs\d+/
             "build/Dab.#{Digest::SHA256.hexdigest(filelist_body_new)}.sln"
           end

def build_project(makefile, project)
  case $toolset
  when 'gmake'
    psystem("make -f ../#{makefile} #{project} verbose=1")
  when /vs\d+/
    psystem("#{$msbuild} #{project}.vcxproj /p:Configuration=Release /p:Platform=Win32 /t:Build")
  end
end

task :remove_autogenerated do
  list = [
    cvm_opcodes,
    cvm_classes,
    cvm_opcodes_debug,
    opcode_docs_file,
    classes_docs_file,
    ffi_file,
    cvm_syscalls,
  ]
  list.each do |file|
    next unless File.exist?(file)

    puts "Remove #{file}"
    FileUtils.rm(file)
  end
end

$shared_spec_code = Dir.glob('test/shared/*.dab')

file cvm_classes => [classes_file, classes_task] do
  psystem("ruby #{classes_task} > #{cvm_classes}")
end

file cvm_opcodes => [opcodes, opcode_task] do
  psystem("ruby #{opcode_task} > #{cvm_opcodes}")
end

file cvm_syscalls => [opcodes, cvm_syscalls_task] do
  psystem("ruby #{cvm_syscalls_task} > #{cvm_syscalls}")
end

file cvm_opcodes_debug => [opcodes, opcode_debug_task] do
  psystem("ruby #{opcode_debug_task} | #{clang_format_app} > #{cvm_opcodes_debug}")
end

file regex_engine_marker => [regex_engine_config, regex_engine_dependency] do
  Dab::RegexEngineDependency.prepare!(root: __dir__)
end

desc 'Download and verify the pinned Regex engine dependency'
task regex_engine_dependency: regex_engine_marker

file makefile => [premake_source, version_file, regex_engine_marker] do
  psystem(premake.to_s)
  FileUtils.mv(original_makefile, makefile)
end

file cdisasm => csources_type['cdisasm'] + [makefile] do
  Dir.chdir('build') do
    build_project(makefile, 'cdisasm')
  end
end

file cvm => csources_type['cvm'] + [makefile, ffi_file] do
  Dir.chdir('build') do
    build_project(makefile, 'cvm')
  end
end

file cffitest => csources_type['cffitest'] + [makefile] do
  Dir.chdir('build') do
    build_project(makefile, 'cffitest')
  end
end

file cdumpcov => csources_type['cdumpcov'] + [makefile] do
  Dir.chdir('build') do
    build_project(makefile, 'cdumpcov')
  end
end

def ci_parallel(inputs)
  ci_index = ENV['CI_PARALLEL_INDEX']&.to_i
  ci_total = ENV['CI_PARALLEL_TOTAL']&.to_i
  return inputs unless ci_index && ci_total

  per_instance = (inputs.count.to_f / ci_total).ceil.to_i
  istart = ci_index * per_instance
  iend = (ci_index + 1) * per_instance
  inputs[istart...iend] || []
end

compiled_stdlib = 'tmp/stdlib.dabcb'

file compiled_stdlib => ($sources + Dir.glob('stdlib/*.dab')) do
  psystem("ruby src/frontend/frontend_stdlib.rb --output=#{compiled_stdlib}")
end

def setup_tests(directory, extension = 'test', frontend_type = nil, extras = [], test_name = nil, direct_run = nil, stdlib: false)
  test_name ||= "#{directory}_spec"
  frontend_type ||= "frontend_#{directory}"
  base_path = "test/#{directory}"
  path = "#{base_path}/*.#{extension}"
  test_file_name = "test_#{test_name}_"
  inputs = Dir.glob(path).sort.reverse
  inputs = ci_parallel(inputs)
  outputs = []
  inputs.each do |input_test_file|
    output_output_file = input_test_file.gsub("#{base_path}/", "tmp/#{test_file_name}").gsub(".#{extension}", '.out')
    outputs << output_output_file
    extra_lib = stdlib ? [stdlib] : []
    file_inputs = $sources + [input_test_file] + extra_lib + $shared_spec_code + extras
    file output_output_file => file_inputs do
      puts '>> '.white + output_output_file.white.bold
      if direct_run.nil?
        psystem("ruby src/frontend/#{frontend_type}.rb #{input_test_file} --test_output_prefix=#{test_file_name} --test_output_dir=./tmp/")
      else
        settings = {
          input: input_test_file,
          inputs: [input_test_file],
          test_output_prefix: test_file_name,
          test_output_dir: './tmp/',
          stdlib: stdlib,
        }
        direct_run.new.run_test(settings)
      end
    end
  end
  task test_name.to_sym => outputs do
    DabTestOutput.summary(test_name, outputs.length)
  end
  task "#{test_name}_reverse": outputs.reverse
end

setup_tests('minitest', 'dab', 'frontend_minitest', [cvm], nil, MinitestSpec)
setup_tests('dab', 'dabt', 'frontend', [cvm, cffitest], 'dab', DabSpec, stdlib: compiled_stdlib)
setup_tests('modern_source', 'dabmtest', nil, [cvm], nil, ModernSourceSpec, stdlib: compiled_stdlib)
setup_tests('format', 'dabft', 'frontend_format', [], nil, FormatSpec)
setup_tests('vm', 'vmt', 'frontend_vm', [cvm, cdisasm], nil, VMFrontend)
setup_tests('disasm', 'dat', 'frontend_disasm', [cdisasm])
setup_tests('asm', 'asmt', 'frontend_asm', [], nil, AsmSpec)
setup_tests('dumpcov', 'test', 'frontend_dumpcov', [cdumpcov])
setup_tests('cov', 'test', 'frontend_cov', [cvm, cdumpcov])
setup_tests('debug', 'test', 'frontend_debug', [cvm], nil, DebugSpec)
setup_tests('compiler_performance')
setup_tests('../examples', 'dab', 'frontend_build_example', [], 'build_examples_spec')
setup_tests('multidab', 'test', nil, [cvm, cdisasm])
setup_tests('decompile', 'test', nil, [cdisasm])

legacy_source_vm_smoke_files = [
  'script/legacy_source_vm_smoke.rb',
  'lib/dab/legacy_source_vm_smoke.rb',
  'test/legacy_source_vm_smoke/contract.json',
  'test/legacy_source_vm_smoke/program.dab',
]

unsafe_ffi_capability_files = [
  'script/unsafe_ffi_capability_smoke.rb',
  'lib/dab/unsafe_ffi_capability_smoke.rb',
  'test/unsafe_ffi_capability/contract.json',
  'test/unsafe_ffi_capability/program.dab',
]

desc 'Validate denied-by-default and explicit-opt-in unsafe FFI behavior'
task unsafe_ffi_capability_spec: [cvm, *unsafe_ffi_capability_files] do
  sh RbConfig.ruby, 'script/unsafe_ffi_capability_smoke.rb'
end

desc 'Compile, assemble, and execute the reproducible legacy source smoke'
task legacy_source_vm_smoke: [cvm, *legacy_source_vm_smoke_files] do
  sh RbConfig.ruby, 'script/legacy_source_vm_smoke.rb'
end

address_sanitizer_files = [
  'script/address_sanitizer_gate.rb',
  'lib/dab/address_sanitizer_gate.rb',
  'test/address_sanitizer/heap_buffer_overflow.cpp',
  'test/native/string_intptr_lifetime.cpp',
  'src/cvm/string_intptr_storage.h',
  regex_engine_marker,
  *unsafe_ffi_capability_files,
  *legacy_source_vm_smoke_files,
]

desc 'Build and validate the dedicated Linux x86_64 AddressSanitizer profile'
task address_sanitizer_spec: address_sanitizer_files do
  sh RbConfig.ruby, 'script/address_sanitizer_gate.rb'
end

undefined_behavior_sanitizer_files = [
  'script/undefined_behavior_sanitizer_gate.rb',
  'lib/dab/undefined_behavior_sanitizer_gate.rb',
  'test/undefined_behavior_sanitizer/signed_integer_overflow.cpp',
  'test/native/string_intptr_lifetime.cpp',
  'src/cvm/string_intptr_storage.h',
  regex_engine_marker,
  *unsafe_ffi_capability_files,
  *legacy_source_vm_smoke_files,
]

desc 'Build and validate the dedicated Linux x86_64 UndefinedBehaviorSanitizer profile'
task undefined_behavior_sanitizer_spec: undefined_behavior_sanitizer_files do
  sh RbConfig.ruby, 'script/undefined_behavior_sanitizer_gate.rb'
end

combined_sanitizer_files = [
  'script/combined_sanitizer_gate.rb',
  'lib/dab/combined_sanitizer_gate.rb',
  'config/combined_sanitizer_gate.json',
  *address_sanitizer_files,
  *undefined_behavior_sanitizer_files,
]

desc 'Run the supported Linux x86_64 sanitizer gates in their checked order'
task combined_sanitizer_spec: combined_sanitizer_files do
  sh RbConfig.ruby, 'script/combined_sanitizer_gate.rb'
end

string_intptr_lifetime_source = 'test/native/string_intptr_lifetime.cpp'
string_intptr_lifetime_binary = "tmp/string_intptr_lifetime_spec#{RbConfig::CONFIG.fetch('EXEEXT')}"

file string_intptr_lifetime_binary => [string_intptr_lifetime_source, 'src/cvm/string_intptr_storage.h'] do
  FileUtils.mkdir_p(File.dirname(string_intptr_lifetime_binary))
  cxx = Shellwords.split(ENV['CXX'] || RbConfig::CONFIG.fetch('CXX'))
  sh(*cxx, '-std=c++11', '-Wall', '-Wextra', '-Werror', '-pedantic',
     string_intptr_lifetime_source, '-o', string_intptr_lifetime_binary)
end

desc 'Build and run the String-to-IntPtr native lifetime regression'
task string_intptr_lifetime_spec: string_intptr_lifetime_binary do
  sh File.expand_path(string_intptr_lifetime_binary)
end

# gitlab = '.gitlab-ci.yml'
# gitlab_base = 'gitlab_base.rb'

# file gitlab => [gitlab_base, 'gitlab_base.yml'] do
#  psystem("ruby #{gitlab_base} > #{gitlab}")
# end

# task :docker do
#  tag = YAML.load_file('gitlab_base.yml')['image']
#  psystem("cd dockerenv && docker build -t #{tag} . && docker push #{tag}")
# end

task dab_fixture_spec: :dab

task :spec do
  psystem('bundle exec rspec')
end

task reverse: :dab_reverse

file opcode_docs_file => [opcodes, opcode_docs_task] do
  psystem("ruby #{opcode_docs_task} > #{opcode_docs_file}")
end

file classes_docs_file => [classes_file, classes_docs_task] do
  psystem("ruby #{classes_docs_task}")
end

file ffi_file => [ffi_task] do
  psystem("ruby #{ffi_task} > #{ffi_file}")
end

task default: [opcode_docs_file, classes_docs_file, cvm, cdisasm, :string_intptr_lifetime_spec,
               :legacy_source_vm_smoke, :unsafe_ffi_capability_spec, :minitest_spec,
               :dab_fixture_spec, :modern_source_spec, :format_spec, :vm_spec,
               :disasm_spec, :asm_spec, :dumpcov_spec, :cov_spec, :debug_spec, :multidab_spec, :decompile_spec] do
end

# :build_examples_spec,

task :clean do
  files = Dir.glob('./tmp/**/*') + Dir.glob('./bin/**/') + Dir.glob('./build/**/*')
  files.each do |file|
    next if file == '.gitkeep'

    if File.file?(file)
      puts "> Remove file #{file}"
      FileUtils.rm(file)
    end
  end
end

task force_clean: %i[remove_autogenerated clean] do
end

def cpp_check
  files = (%w(cpp mm m h).map { |ext| Dir.glob("src/**/*.#{ext}") }).flatten(1)
  files.each do |file|
    yield(file)
  end
end

def cpp_check_format
  cpp_check do |file|
    unless file[/default/]
      yield(file)
    end
  end
end

namespace :format do
  task :ruby do
    psystem('bundle exec rubocop >/dev/null 2>/dev/null || bundle exec rubocop -a')
  end

  task :cpp do
    cpp_check_format do |file|
      psystem("(#{clang_format_app} #{file} | diff #{file} -) || #{clang_format_app} -i #{file}")
    end
  end

  task :cpp_force do
    cpp_check do |file|
      psystem_ignore("#{clang_format_app} -i #{file}")
    end
  end

  task :cpp_check do
    cpp_check do |file|
      psystem("#{clang_format_app} #{file} | diff #{file} -")
    end
  end

  task stdlib: $sources do
    files = Dir.glob('./stdlib/**/*.dab')
    files.each do |file|
      psystem("ruby src/format/format.rb < #{file} > #{file}.format; mv #{file}.format #{file}")
    end
  end

  task stdlib_check: $sources do
    files = Dir.glob('./stdlib/**/*.dab')
    files.each do |file|
      psystem("ruby src/format/format.rb < #{file} | diff #{file} -")
    end
  end

  task :sort do
    psystem('ruby ./tasks/sort.rb')
  end

  task :sort_check do
    psystem('ruby ./tasks/sort.rb --check')
  end

  task :sortfiles_check do
    psystem('ruby ./tasks/sortfiles.rb')
  end
end

task format: ['format:sort', 'format:ruby', 'format:cpp']

task :master do
  psystem('git multipush github master; git branch -f master github/master')
end

task :dev do
  psystem('git multipush origin master --force')
end

task :example, [:number] => [cvm, cdisasm] do |_t, args|
  number = args[:number]
  input = Dir.glob(sprintf('examples/%04d*', number)).select { File.file?(_1) }.first
  if input
    psystem("ruby src/frontend/frontend_example.rb #{input}")
  else
    psystem("ruby src/frontend/frontend_example_new.rb #{number}")
  end
end

task :benchmark do
  psystem("git-benchmark performance-base..HEAD 'timeout 5 ruby src/compiler/compiler.rb tmp/test_compiler_performance_spec_0002_bigger_random.dab'")
end
