require_relative '../src/shared/classes'

puts '// Autogenerated from /src/shared/classes.rb'
puts
puts 'enum'
puts '{'

object_map = STANDARD_CLASSES.each_with_index.map do |v, k|
  [k, v]
end.to_h

max_name_len = object_map.map { |_k, v| v.length }.max

format = "    CLASS_%-#{max_name_len}s = %d,\n"

object_map.each do |key, name|
  printf(format, name.upcase, key)
end

puts '};'
