require_relative '../src/shared/opcodes.rb'

puts '// Autogenerated from /src/shared/opcodes.rb'
puts

puts 'const DabOpcodeInfo g_opcodes[] = {'

format = "    {OP_%s, \"%s\", {%s}},\n"

REAL_OPCODES.each_value do |opcode|
  name = opcode[:name]
  args = if opcode[:args]
           opcode[:args]
         else
           [opcode[:arg]].compact
         end
  args = args.map { |arg| "OpcodeArg::ARG_#{arg.upcase}" }
  args = args.join(', ')
  printf(format, name, name, args)
end

puts '};'
