require_relative '../src/shared/opcodes.rb'

puts '// Autogenerated from /src/shared/opcodes.rb'
puts
puts 'enum'
puts '{'

max_name_len = OPCODES.map { |_k, v| v[:name].length }.max
max_value_len = OPCODES.map { |k, _v| sprintf('%x', k).length }.max

format = "    OP_%-#{max_name_len}s = 0x%0#{max_value_len}X,\n"

OPCODES.each do |key, opcode|
  name = opcode[:name]
  printf(format, name, key)
end

puts '};'
