// Autogenerated from /src/shared/classes.rb

enum
{
    CLASS_OBJECT     = 0,
    CLASS_STRING     = 1,
    CLASS_FIXNUM     = 2,
    CLASS_BOOLEAN    = 3,
    CLASS_NILCLASS   = 4,
    CLASS_ARRAY      = 5,
    CLASS_UINT8      = 6,
    CLASS_UINT16     = 7,
    CLASS_UINT32     = 8,
    CLASS_UINT64     = 9,
    CLASS_INT32      = 10,
    CLASS_METHOD     = 11,
    CLASS_INTPTR     = 12,
    CLASS_BYTEBUFFER = 13,
};
