// Autogenerated from /src/shared/classes.rb

enum
{
    CLASS_OBJECT        = 0,
    CLASS_STRING        = 1,
    CLASS_FIXNUM        = 2,
    CLASS_BOOLEAN       = 3,
    CLASS_NILCLASS      = 4,
    CLASS_ARRAY         = 5,
    CLASS_UINT8         = 6,
    CLASS_UINT16        = 7,
    CLASS_UINT32        = 8,
    CLASS_UINT64        = 9,
    CLASS_INT8          = 10,
    CLASS_INT16         = 11,
    CLASS_INT32         = 12,
    CLASS_INT64         = 13,
    CLASS_METHOD        = 14,
    CLASS_INTPTR        = 15,
    CLASS_BYTEBUFFER    = 16,
    CLASS_LITERALSTRING = 17,
    CLASS_DYNAMICSTRING = 18,
    CLASS_FLOAT         = 19,
    CLASS_FUNCTION      = 20,
};
