// Autogenerated from /src/shared/opcodes.rb

enum
{
    CLASS_OBJECT        = 0,
    CLASS_STRING        = 1,
    CLASS_LITERALSTRING = 2,
    CLASS_FIXNUM        = 3,
    CLASS_LITERALFIXNUM = 4,
    CLASS_BOOLEAN       = 5,
    CLASS_NILCLASS      = 6,
    CLASS_ARRAY         = 7,
    CLASS_UINT8         = 8,
    CLASS_INT32         = 9,
    CLASS_METHOD        = 10,
    CLASS_UINT64        = 11,
    CLASS_UINT32        = 12,
};
