// Autogenerated from /src/shared/opcodes.rb

enum
{
    KERNEL_PRINT         = 0x0,
    KERNEL_EXIT          = 0x1,
    KERNEL_USECOUNT      = 0x2,
    KERNEL_TO_SYM        = 0x3,
    KERNEL_FETCH_INT32   = 0x4,
    KERNEL_DEFINE_METHOD = 0x5,
    KERNEL_BYTESWAP32    = 0x6,
    KERNEL_DLIMPORT      = 0x7,
    KERNEL_WARN          = 0x8,
    KERNEL_DEFINE_CLASS  = 0x9,
    KERNEL_GET_INSTVAR   = 0xA,
};
