FROM ubuntu:16.10
RUN apt-get update 
RUN apt-get install -y g++-4.7
RUN apt-get install -y g++-4.8
RUN apt-get install -y g++-4.9
RUN apt-get install -y g++-5
RUN apt-get install -y g++-6
RUN apt-get install -y git
RUN apt-get install -y ruby2.3 ruby2.3-dev
RUN apt-get install -y clang-3.5
RUN apt-get install -y clang-3.6
RUN apt-get install -y clang-3.7
RUN apt-get install -y clang-3.8
RUN apt-get install -y clang-3.9
